name: 📰 Release newsletter

on: workflow_dispatch

jobs:
  style-checks:
    permissions:
      id-token: write
      contents: write

    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release latest draft
        run: python3 scripts/release.py
      - name: Make next draft
        run: python3 scripts/make_new_draft.py
      - name: Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Release issue"
          git push https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/rust-scicomp/scientific-computing-in-rust-monthly.git
