name: 🕶️ Style

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install ruff
        name: Install requirements
      - run: python3 -m ruff check .
        name: Run ruff checks
      - run: python3 -m ruff format --check .
        name: Run ruff checks
